### ISSUE TITLE
Improve figures bias

### ISSUE THREAD

**Issue by fsaintjacques** [oertl/hyperloglog-sketch-estimation-paper#2]
I find it non trivial to compare figures between multiple estimation functions. I would recommend to take a look at multiple boxplot for achieving this, e.g. https://pvk.ca/Blog/2012/07/03/binary-search-star-eliminates-star-branch-mispredictions/

There's also this variant: https://pvk.ca/Blog/2014/04/13/k-ary-heapsort/

**Comment by oertl** [comment]
Thanks, for the feedback. I've added this to my todo list. A comparison of different cardinality estimators for selected cardinality values would be definitely an enrichment.

**Comment by fsaintjacques** [comment]
I suggest to do the same for runtime execution of each estimator. Having 'raw' runtime numbers without basis for comparison is near useless.

**Comment by oertl** [comment]
A fair comparison of different algorithms is difficult, because the numbers strongly depend on the implementation and how much effort is put on its optimization. The main goal of the execution time charts is to show the behavior of the same algorithm over the true cardinality for different HyperLogLog parameters. The numbers also do not include the time to calculate the multiplicity vector, which requires a full scan over all HyperLogLog registers. In order to have a number for comparison, the paper includes a theoretical lower bound due to the limited memory bandwidth, which was at least 120ns (for p=12) on my machine. This is the minimum time to load the HyperLogLog data structure from main memory. For comparison the corrected raw estimation algorithm (p=12, q=20) with lookup tables for sigma and tau, takes approximately 130ns.

It can be expected that the execution time of the corrected raw estimation algorithm using lookup tables is more or less the same as for the calculation of the raw estimate, because the two extra array lookups are very fast. Therefore, any estimation algorithm as the original method by Flajolet requiring the calculation of the raw estimate cannot be really faster.

**Comment by oertl** [comment]
Closing this issue. I will not add a runtime comparison of different estimation algorithms. The primary purpose of the existing runtime charts is to show the qualitative behavior.
